### ISSUE TITLE
Small Eldritch Cannon lacking stat/level scaling

### ISSUE THREAD

**Issue by Pterosquirrel** [Kidel/BG3_Artificer#103]
Currently there are only two separate templates for the mobile cannon, at levels 3 and 9. Both stages are using a base Intelligence score of 15 to calculate to-hit and save bonuses. Since on tabletop these are based on the Artificer's stats+PB, there should probably be additional summoning stages to reflect expected stat progression. The independent cannon is currently rather weak past 5th level because it's falling behind after ASIs and proficiency bonus increases (~20-30% weaker compared to TT/hand cannon variant).

I'm thinking additional variants for at least 5th and 15th levels (and a slight buff to the 9th level one) to match Steel Defender level stages. Something like:
* 5th: 16 INT (PB +3)
* 9th/12th: 18 INT (PB +4)
* 15th: 20 INT (PB +5)

You could have 20 INT by 5th level already, but these are more conservative estimates assuming someone might take feats or multiclass.

**Comment by Pterosquirrel** [comment]
Possible alternative for avoiding code bloat: Give Artillerists a "Charge Cannon" bonus action to increase the cannon's hit modifier and save DC? Truer to the source material as well.

**Comment by Kidel** [comment]
is it still the case after we added the new endgame gear?

**Comment by Pterosquirrel** [comment]
Haven't had the chance to test the new endgame gear yet so I can't offer much insight on those yet. It's still prominent for midgame progression though, starting around the close of Act 1 going into Act 2. 5th level is normally a pretty big power bump for most classes, but the cannon can't use the Artillerist's stats like it does on TT so it's stuck with its lower attack rolls and saving throws for quite a few levels around midgame.

**Comment by Kidel** [comment]
to compensate for that we gave it all 3 abilities instead of just one. So it can be a pretty nice supporter until you bump into the next powerup.

**Comment by Pterosquirrel** [comment]
Thanks for giving it another look! In my experience, while the versatility is nice, it often feels underwhelming because most of the options end up being somewhat subpar for their intended purpose.
