### ISSUE TITLE
Request: Add the Warforged race for players.

### ISSUE THREAD

**Issue by Endarire** [Kidel/BG3_Artificer#106]
Greetings, all!

Warforged are one of my favorite D&D races, and the automaton from the Artificer class kinda looks like a Warforged.  What say you to adding this thematically compatible race?

From a technical perspective, I'm unsure at present what would be involved in adding this race, or whether it would be better as a separate mod.

Thankee!

**Comment by Kidel** [comment]
I'd love a warforged race from Eberron. However it seems a bit out of the scope of this mod. I'm sure someone will work on that eventually.
