### ISSUE TITLE
Request: Add the Reverse-Engineer Subclass

### ISSUE THREAD

**Issue by Moik-sama** [Kidel/BG3_Artificer#107]
One of the funnest subclasses to play for the artificer in my opinion is the one from this homebrew content made by a friend of mine the class is called [Reverse-Engineer](https://homebrewery.naturalcrit.com/share/LUTNdymR_) and it brings a new and fun way to play the artificer, it allows the player to play the class in general as either close range, mid range or long range magic caster thanks to the features and spells we get from it.

You can find it in page 5 of the small booklet he made in that webpage.

**Comment by Kidel** [comment]
Sounds super cool, I'll ask my DM if I can play it. However we won't add HB content in this mod, sorry :( 

I can still take some of those ideas and incorporate them into gear and stuff. We are kind of using that for HB/UA ideas, kind of like Larian would do.
