### ISSUE TITLE
Remove the "I wish I had a bag of holding" voiceline

### ISSUE THREAD

**Issue by XDracam** [Kidel/BG3_Artificer#109]
It's slightly immersion breaking when Tav is stuffing sausages into their quality artificer bag of holding ™️ while saying "I wish I had a bag of holding".

This is it. This is the issue. A minor request to remove that voiceline when the character does, in fact, have a bag of holding.

Feel free to ignore if this is not worth your time, haha. Thanks for the great mod!

**Comment by Kidel** [comment]
I won't even know where to start from lol.
