### ISSUE TITLE
Unable to shoot arrows

### ISSUE THREAD

**Issue by sztrzask** [Kidel/BG3_Artificer#114]
I am unable to shoot arrows. The issue started happening after adding both Artificer and the 5e spells optional file.

The following is my mod list.

![image](https://github.com/Kidel/BG3_Artificer/assets/4059524/1c4ebaa6-1488-4514-9f8e-7bb307a7828e)

(I can also send my save if that could help).

**Comment by Kidel** [comment]
There is a guide on how to solve this on the mod forum on Nexus. It looks like a save compilation issue when you update the game with the mod installed.

**Comment by sztrzask** [comment]
> There is a guide on how to solve this on the mod forum on Nexus. It looks like a save compilation issue when you update the game with the mod installed.

Fresh game, fresh mods, for Patch 7 - issue still persists. If I start a new game with Artificer mods it works fine for some time, then randomly it will start happening again mid act-1. If I don't have Artificer mod, the issue never happens.

Current modlist:
![image](https://github.com/user-attachments/assets/7bea9e0c-dd5f-45d5-8c8c-f81ac6078c15)
