### ISSUE TITLE
Steel Watcher summon on Armorer still has the Failsafe Protocol, activates on enviroment turn

### ISSUE THREAD

**Issue by RumekFuria** [Kidel/BG3_Artificer#115]
Title
Despite the inspect tab not showing it as a feature or anything, the mini-watcher will self detonate on low hp
This would be fine, and even maybe a cool feature to make this a proper "MK2 Automata"... Cept the detonation starts on environment turn, and explodes straight away on it's own turn, not giving a chance to prevent undesirable Friendly Fire, considering Pack Tactics

**Comment by Kidel** [comment]
This looks to be hardcoded in the game when your creature is a Steel Watcher. 
I suppose you can think of it as "it's not a bug, it's a feature" kind of thing :D

**Comment by RumekFuria** [comment]
I don't mind it being there overall, it's just the "environment turn to self turn start" part that can easily mess things up

If it's hardcoded, so be it, but it would be nicer if there was at least _some_ extra time to either move it, or others, into a more favorable position

**Comment by Kidel** [comment]
I feel you ahah, but it's still funny for immersion :) 
I kind of like that it's not just a skin change but adds something.
