### ISSUE TITLE
Protector Cannon 

### ISSUE THREAD

**Issue by tomcool420** [Kidel/BG3_Artificer#116]
I noticed a couple of issues with protector cannon ability:

- it's set at once per combat usage when it should be once per round
- it heals for a different amount (4+PB vs 1d8+int modifier)

Are those decisions that were made on purpose? I imagine the second is so that the standalone canon works properly in BG3 but the first one seems like a large utility loss for support artificers

**Comment by Kidel** [comment]
This is one of the intended changes in the readme, and it's done to balance the fact that you don't pick 1 type of cannon, but instead you get a cannon with all its abilities.
