### ISSUE TITLE
Patch 7 Compatibility

### ISSUE THREAD

**Issue by RandoRuda** [Kidel/BG3_Artificer#119]
My attempt at trying to get a quick fix out for Artificer didn't work as planned. Some of the backwards compatibility stuff seems to break if I move the icons to the updated  locations - I'm not sure why it would impact the default armour and such, but it did.
![image](https://github.com/user-attachments/assets/898c3f9a-aa07-4a4e-b9cb-30c2e61a075d)

Removing the in built Mod Fixer is a simple fix that will make it workable until I can finish doing the complete update into the toolkit to address everything. The class icons might not work, but it's better than other random stuff seemingly acting weird.
![image](https://github.com/user-attachments/assets/32a3e042-5906-4899-b360-443edeab13d3)

**Comment by Kidel** [comment]
Should be handled now. I checked that the armor works on every class. 
Thanks for your help!
