### ISSUE TITLE
Implement starting equipment for base Artificer

### ISSUE THREAD

**Issue by Pacted** [Kidel/BG3_Artificer#13]

**Comment by DrBoskonovitch** [comment]
The Ringmail armor in the starting equipment is heavy, which artificers aren't proficient with.

**Comment by Kidel** [comment]
True, will change to medium and use a different name.

**Comment by Kidel** [comment]
![image](https://github.com/Kidel/BG3_Artificer/assets/3390842/4a257dac-91ec-4e41-9838-a66d233eca4e)

**Comment by Kidel** [comment]
done
