### ISSUE TITLE
Implement Infusions

### ISSUE THREAD

**Issue by Pacted** [Kidel/BG3_Artificer#15]
(get from http://dnd5e.wikidot.com/artificer:infusions). Infusion are learned but must be prepared. Not all infusions are interesting. Most of them can be skills copied from Pact of the Blade, Shillelagh and Goodberry (so items can't be stockpiled). I'd make most non-permanent infusions (basically all of them) as free action so that can be used in fight if people forget to re-conjure them after long rest.

  - [-] Arcane Propulsion Armor -> infuse armor with an effect that increases speed by 5feet.
  - [-] Armor of Magical Strength -> infuse armor with passive that gives Prone immunity and advantage on Strength checks.
  - [x] Boots of the Winding Path -> infuse boots with Misty Step skill unlock. Could be moved to replicate magic items for simplicity
  - [x] Enhanced Arcane Focus -> infuse weapon to get +1 to spell attack rolls.
  - [x] Enhanced Defense -> shield or armor give +1 to AC, +2 after level 10.
  - [x] Enhanced Weapon -> weapon gives +1 to attack and damage, +2 after level 10.
  - [x] Homunculus Servant -> fast way would be Find Familiar, custom models in the future.
  - [x] Radiant Weapon -> like Enhanced Weapon (except the +2) but also unlocks Light cantrip.
  - [x] Repeating Shot -> +1d4 force damage to ranged weapon.
  - [-] From 6th level: Repulsion Shield -> once the shield is infused, adds reaction spell to melee attacks to push 15 feet away (might be overpowered to give 4 charges, I'd nerf it to once per fight).
  - [x] From 6th level: Resistant Armor -> gives resistance to one damage type, might get the submenu too long, can we make container spells of container spells?
  - [x] From 6th level: Returning Weapon -> adds returning effect to weapon.
  - [x] From 6th level: Spell-Refueling Ring -> conjure a ring that refuels 1 spell slot once per day, I think this is boring to infuse and then cast, I'd change it to just convert 1 Infusion Slot to 1 Spell Slot. 
  - [x] Replicate Magic Item -> oh boy.
    - [x] Bag of Holding: unclear if the game allows for the fixed weight "regardless of contents" and it's not really useful in BG3. I'd just replace it with a spell that costs 2 infusion and replicates Gale's explosion, just for the lol (it's what happens if you put a Bag of Holding inside another).
    - [x] Other magic items we might want to make, some examples:
      - [-] Googgles of Night -> passive darkvision up to 60 feet.
      - [-] Necklace of Secrets -> replaces wand of secret, gives a bonus to Investigation and Perception.
      - [-] From 6th level: Staff of Defense -> allows cast of Mage Armor and Shield.
      - [-] From 6th level: Cloak of Elvenkind -> unlocks pass without trace.
      - [-] From 6th level: Gloves of Thievery -> +5 to SleightOfHand
      - [x] From 10th level: Amulet Of Health -> this is already in the game.
      - [x] From 10th level: Gauntlets of Giant Strength -> this is already in the game.
      - [-] From 10th level: Cape Of The Mountebank -> allows casting of Dimension Door once per long rest.
      - [-] From 10th level: Helm of Brilliance -> allows casting of FireBall once per long rest.
      - [x] From 10th level: Winged Boots -> can fly
      - [x] From 10th level: Helm of Telepathy -> can cast Detect Thoughts and Counterspell

**Comment by Rumsarr** [comment]
Bag of Holding: unclear if the game allows for the fixed weight "regardless of contents"

There is a 'Chest of the Mundane' that turns all items within into light mundane objects.  perhaps a tweak can make it into a bag of holding somehow?

**Comment by Rumsarr** [comment]
As for infusions themselves would it be posable to add an additional equip slot for infusions?

The nature of the artificer is to share infusions with the party.  So giving all the other characters 'infusion slots' would allow for that to work would it not?

**Comment by Rumsarr** [comment]
The more I think on it, the more I believe that additional equipment slots would be better for infusions as a whole.  It might even sync with the game programing in general too.  But that's just a hunch.

**Comment by Rumsarr** [comment]
Infusions in general are pretty powerful, but an artificer only has a very limited amount of them. So let them be powerful as it is the main facet of being that class

**Comment by Rumsarr** [comment]
https://www.nexusmods.com/baldursgate3/mods/1303

New mod that came out might be helpful with working on infusions

**Comment by Rumsarr** [comment]
So, what's the plan for infusions?  Are we making them buffs?  Increasing the inventory slots for infusions so we can put them in all PC's inventory?

If we are going to make them buffs we will need more/different concentration slots for the infusions.

If we are going to put them in inventory slots we can use the sorcerer meta magic system to break down infusions in order to get the infusions points back.

**Comment by Kidel** [comment]
whatever works. 3 infusions already in:
Enhanced Weapon -> weapon buff
Enhanced Armor -> character buff that requires equipped armor
Enhanced Focus -> character buff

Some will spawn items, some will give buffs

**Comment by Rumsarr** [comment]
The enhanced armor/weapon are we going to restrict the infusions to non-magical items or just ignore that?

**Comment by Kidel** [comment]
they ignore for now, but maybe it can be added.

**Comment by Rumsarr** [comment]
might be safe to ignore if it only gives +1 at all times.

**Comment by Kidel** [comment]
bag of holding moved from replicate magic item to infusion of your actual bag for technical reasons

**Comment by Rumsarr** [comment]
A lot of the 10th level infusions will needs to be looked at.  They are suppose to be the very best of the infusions that an artificer can create. and some need adjustment. 

**Helm of telepathy**: Needs more then just the 2nd level spell, detect thoughts.   As a 10th level infusion it will need a boost to make it worth even thinking about. Giving advantage on   Deception, persuasion, and Insight checks would make it a contender in picking for an infusion.

**Helm of Brilliance**: In DnD it can cast daylight, fireball, prismatic spray, and wall of fire. All of these spells are powerful for sure and being able to cast all might need tweaking. But just fireball makes the infusion not worth getting unless its casted at a very high level.

**Cape Of The Mountebank**:  Might want to consider moving this to the 6th lvl infusions.

I think we need more variety for the most powerful infusions. As is, only winged boots are even worth thinking about.

**Comment by Rumsarr** [comment]
Other infusions to think on.

Cloak of protection: in the game
Gloves of missile snaring: in the game (act 1 no less)
Ring of jumping: in the game.
Ring of mind shielding: in the game (act 2)
Headband of intellect: in the game.

**Comment by Rumsarr** [comment]
Actually thinking on how free BG3 is giving out supposedly 'rare' magic items like candy we might want to shift all infusion by 1 level.   14 to 10 and so on. Thought it seems we already seem to be doing some of that.

**Comment by Kidel** [comment]
agreed. Balancing will sure be done.

**Comment by Rumsarr** [comment]
Maybe we can find an item list, and look at all the stuff then just replicate those in the game?

2 does green items
6th does blue
and 10th does purple?

Then we can just pick from a list of a some good ones that are 'artificer flavored' that would work then replicate those?

**Comment by Rumsarr** [comment]
Sure we can still use some that we already made but the rest? Could be a snap.

**Comment by DrBoskonovitch** [comment]
Instead of "Repeating Shot -> +1d4 force damage to ranged weapon." what do you guys think of allowing an extra shot as a bonus action?

**Comment by Kidel** [comment]
with the stuff I know now, I'd probably do something even different. 

I'd change the projectile type with a force one and I'd make the damage higher. Affecting the weapon directly.

**Comment by Rumsarr** [comment]
Its not a bad idea except is stomps into the thief subclass's whole shtick.

**Comment by Rumsarr** [comment]
Maybe instead of repeating shot maybe explosive shot?   give it a small aoe like Ice knife?

**Comment by DrBoskonovitch** [comment]
Or maybe a small knockback?

**Comment by Kidel** [comment]
I'd try to stay close to the manual as much as possible. We are making the Artificer, not a custom class please. 

The reloading property removal is tricky. We could either bump the damage up or we could add a second skill as a bonus action so that you can do more attacks.

**Comment by DrBoskonovitch** [comment]
That's a fair point

**Comment by Rumsarr** [comment]
what about do 2 targets like eldritch blast? or double tap one?

**Comment by Kidel** [comment]
if it's a 1v1 you get no benefit from not having to reload

**Comment by Kidel** [comment]
yeah that's even better because you don't waste the bonus action

**Comment by DrBoskonovitch** [comment]
Can you make the multiple shot be able to hit the same target, like magic missiles?

**Comment by Kidel** [comment]
yes definitely. I'd just copy magic missile, remove the "homing" trajectory and limit the targets to 2

**Comment by DrBoskonovitch** [comment]
"Plus just 1 spell to make and have it replace the base ranged one."
That would be doubling damage output and be pretty OP.  The way I implemented it is that once per turn you can do a special attack that lets you pick two targets.  It can replace one of your attacks, if you have multiple attacks.

**Comment by Kidel** [comment]
yeah that's better

**Comment by Kidel** [comment]
finished the system to target weapons and armors with buffs, and then add extra effects to the characters based on those buffs. Allows to realistically make repeating shot and all infusions that add a skill/spell to an item, as well as armor/shield with bonus ac. 

plus if you give the item to a companion the effect transfers to it. 

The only drawback is that it takes the end of the user's turn to check for the buff in inventory, unless we add a passive for check on equip and on cast.

**Comment by Kidel** [comment]
so, the game doesn't really allow for multiple "select spells" that are not cantrips or prepared spells. It really only allows for multiple "add spells" with a fixed roster. 

There is also the fact that we are not able to allow infusion swap.

**_I'll test it more_**, but if it's the case I suggest we re-think our infusion list and simply add them all at lv2, 6, 10.

**Comment by Kidel** [comment]
In typical Larian style, let's make smart cuts to the infusion system

Level 2:
Already implemented (no need to cut): Enhanced Arcane Focus, Enhanced Defense (auto-upgraded to lv10), Enhanced Weapon (auto-upgrades too), Homunculus Servant, Radiant Weapon, Repeating Shot

TODO: Boots of the Winding Path
I won't add more, because having to pick 4 here is prretty hard. Plus we'd have already 5 effects in the aura checks. 

Level 6:
Already implemented: Returning Weapon. This is pretty awesome for certain builds (maybe not for the artificer, but it's great support).

I'd cut repulsion shield, as most Shields in the game past Act1 already have that effect. 

Resistant armor is interesting but I'd give it resistance to all elements at once instead of developing 10 spells, 10 passives, etc. If it's too powerful it's better to just cut it. 

Spell-refueling ring -> changed to Spell-refuel and just trades 1 infusion for 1 spell slot, can be copied from the same spell from Sorcerer. 

I'd cut all lv 6 magic items since they're pretty meh. 

Leel 10
Replicate Magic Item -> changed to a container spell that unlocks all possible items replications. 
Gauntlets of Giant Strength -> pretty great, already in the game
Cape Of The Mountebank -> pretty great
Helm of Counterspell -> unlocks counterspell, since the Artificer doesn't have it normally
Winged boots -> unlocks fly
Headband of Intellect -> 19 Intelligence override, good for tank builds to also spellcast. Already in the game
 
meaning we're just missing: 
Boots of the Winding Path, Resistant armor, Spell-refueling ring, Replicate Magic Item
I can do the first 2 since they use the aura system

**Comment by Kidel** [comment]
meaning we're just missing:
Boots of the Winding Path, Resistant armor, Spell-refueling ring, Replicate Magic Item
I can do the first 2 since they use the aura system

**Comment by Kidel** [comment]
just missing 1 icon for replicate magic item + boots of winding path
