### ISSUE TITLE
Implement Flash of Genius

### ISSUE THREAD

**Issue by Pacted** [Kidel/BG3_Artificer#16]
similar to Guidance Cantrip

**Comment by Kidel** [comment]
I pushed a version of Flash Of Genius as 2 reactions (one triggered on saving throw, one on attack/spell). Both add PB to the roll of an ally
(which is the same passive, so the double reaction is just whichever triggers first)
needs to be tested
it's pushed to main and already learned at level 7

**Comment by Kidel** [comment]
done it as skill (using reaction resource) and as reaction (interrupt) 

![image](https://github.com/Kidel/BG3_Artificer/assets/3390842/67173ce4-fa28-4c72-aabf-0681718929c2)
![image](https://github.com/Kidel/BG3_Artificer/assets/3390842/dd49f3f0-01d3-40ff-b820-088cde07c073)
