### ISSUE TITLE
Implement Magic Item Adept

### ISSUE THREAD

**Issue by Pacted** [Kidel/BG3_Artificer#17]
create a magic item once per long rest using Gold or a Magic Item resource

**Comment by Rumsarr** [comment]
Another option might be to be able to use the magic items the character has more then once.  Or maybe be able to use all magic items as a bonus action.  Its a 10th level ability so it would be basically a capstone ability.

**Comment by Kidel** [comment]
I made a version of this called Chemical Adept, as magic items are super strong in the game, and replicating them would make the class too op, while having weaker versions of them would make them useless. 

Chemical Adept allows you to create a wide variety of explosives and vials. I'm open to ideas, but for the time being this is cool. 

Unfortunately I wasn't able to have it consume resources/gold as I wanted.

**Comment by Rumsarr** [comment]
I think that would be great theming for an alchemist and we can totally use that.  What can we make that could let the other subclass pop like that?

**Comment by Kidel** [comment]
it's not alchemy, so I think it's fitting for the base class too. Also considering that any class in bg3 can do alchemy.
