### ISSUE TITLE
Implement Spell/cantrip progression of base Artificer up to level 12

### ISSUE THREAD

**Issue by Kidel** [Kidel/BG3_Artificer#2]
Missing abilities can be skipped for now. The goal is to have a complete skeleton. 
For missing ones we can leave comments in the lsx, so we already know where to add stuff later.

**Comment by Rumsarr** [comment]
Magical Tinkering (1st level) 
The artificer equivalent of  prestidigitation, druid craft, and other unique spells that usually require a DM's insight to actually pull off.   Perhaps just adding a few features as cantrips might help out in that regard.  In the game that might not be that big of an issue
Light and minor illusion come to mind and would be an ok substitute in game.

Right Tool for the Job
I would suggest just summoning a tool would work here either a thieves' tools or a disarm tools as these are the only real tools in the game that players can use.  There are plenty of both to be found so summoning more wouls be that big of an issue or game breaking.

Tool Expertise
A simple bonus to making disarm checks or picking checks could be useful.

Flash of Genius
Would work like guidance only would need to keep them limited to a number per long rest. 

Magic Item Adapt
Attunement is not implemented in BG3 and item creation would have to be a completly new system.
As a compromise, perhaps adding 1 or two more infusion slots would be suitable. 

Spell Storing Item
Scroll creation would work in most cases with this.

**Comment by DrBoskonovitch** [comment]
I have The Right Tool for the job implemented locally.  It summons thieves tools, trap disarming kit, or shovel once per short rest.  I'm a github noob, I have to figure out how to upload it.

**Comment by Rumsarr** [comment]
Ah shovel!  good idea
