### ISSUE TITLE
Implement Battle Ready

### ISSUE THREAD

**Issue by Pacted** [Kidel/BG3_Artificer#20]
magic weapons use Intelligence instead of Strength or Dexterity, see Pact of the Blade

**Comment by Kidel** [comment]
![Image](https://github.com/Kidel/BG3_Artificer/assets/3390842/9d5c7df6-7b82-4c34-bc83-b8d661de6c4c)


![Image](https://github.com/Kidel/BG3_Artificer/assets/3390842/d8aa0ecd-e18d-4e7b-bc84-1fcb12b0f04e)

**Comment by Kidel** [comment]
![Image](https://github.com/Kidel/BG3_Artificer/assets/3390842/e956206d-9d16-402e-a07b-1b3088773f1a)
