### ISSUE TITLE
Implement Perfected Armor

### ISSUE THREAD

**Issue by Pacted** [Kidel/BG3_Artificer#29]
(could be a magically crafted armor or a status to an existing equipped armor, similar to Pact of the Blade). Container should allow selection of 2 effects:
  - [ ] Guardian Armor gives 2 skills: Thunder Gauntlets and Defensive Field. Thunder Gauntlets is an unarmed strike attack that's basically 1d8 Thunder Distracting Strike. Defensive Field is just temp hit points passive added to the armor. 
  - [ ] Infiltrator Armor gives 3 skills/passives: Lightning Launcher, Powered Steps and Dampening Field. Lightning Launcher is similar to Which Bolt, but the extra cast doesn't cost an action, Powered Steps and Dampening Field are easy passive bonuses.

**Comment by Rumsarr** [comment]
Maybe create an item that can combine with mundane armor using the in-game creation system?  It would require the creation of light, medium, and heavy types of armor.

**Comment by kreios86** [comment]
Arcane Armor Shout skeleton added to Armorer Push #65

**Comment by Kidel** [comment]
@G-Vie any news?
