### ISSUE TITLE
Armor Modifications

### ISSUE THREAD

**Issue by Pacted** [Kidel/BG3_Artificer#31]
Armor Modifications makes no sense in BG3, an easy rebalance could be to simply add 2 more Infusion Slots. Or we can scrap it and give Perfected Armor

**Comment by Rumsarr** [comment]
If we could add infusion slots to the character loadout screen it would be easier to give +2 slots would it not?

**Comment by G-Vie** [comment]
Rather than 2 infusion slots, it should be possible to make 2 infusions per day free so long as they're cast on armor pieces.

**Comment by Rumsarr** [comment]
2 types of infusions, normal ones that can be 'cast' on everyone and 2 that are self cast only might be better to implement.

**Comment by Kidel** [comment]
have the armor unlock a spell that can be used once a day to recover infusions?

**Comment by Kidel** [comment]
or just give perfected armor instead.

**Comment by kreios86** [comment]
Initial Passive Skeleton for Armor Modifications added to Armorer Push #65

**Comment by Kidel** [comment]
replacing this with a weaker version of Perfected Armor
