### ISSUE TITLE
Implement Eldritch Cannon

### ISSUE THREAD

**Issue by Pacted** [Kidel/BG3_Artificer#32]
easy way: conjure a cannon ranged weapon that gives skills equivalent to Flaming Hands, Eldritch Blast and False Life, hard way: make a pet that looks like a cannon

**Comment by Rumsarr** [comment]
Could the cannon be a shrunken down version of the constructs found in the underdark tower in act 1?

**Comment by Rumsarr** [comment]
Maybe a mobile version of the arcane turret would also work.  shrunken down of course.

**Comment by Kidel** [comment]
also notice it's an object, which might be better than a pet

**Comment by Kidel** [comment]
nvm I made it. Gonna push it soon

**Comment by Rumsarr** [comment]
ROCK ON!

**Comment by DrBoskonovitch** [comment]
Noice!

**Comment by Rumsarr** [comment]
Now all that is left on the turret is to shrink it down somehow, give it it's own movement (misty step?), and deal with the fact that it can only fire on the artificers bonus action.  If that cannon be done then we will need to tone down the damage

**Comment by Kidel** [comment]
misty step is too op, I'd just give it movement, which is not hard, but it's a gameplay decision. 
shrink down might be easier said than done. 
act on bonus action has been scrapped by larian on all summons, so we'll just make it act independently.

**Comment by Rumsarr** [comment]
Then I'd think dropping the dice for the d8 to a d4.  Still useful but won't be overpowering and the extra d4 can still be added at 9th level.

**Comment by Rumsarr** [comment]
Explosive Cannon will also need to be toned down.   For balancing.

**Comment by Kidel** [comment]
not sure, balancing can be done at the end. Larian has powered up a lot of summons

**Comment by Rumsarr** [comment]
Mechanically, what this is doing is basically giving the artificer an extra bonus action as with the thief class. But, it has none of the drawbacks of the 'offhand' strike.

**Comment by Kidel** [comment]
I agree, but we'll have to see, because both pets with 5e stats now are very underpowered. They have like 5% chance of hitting a lv10 enemy. 
Definitely needs rebalancing but it's premature. 

Also I don't think the engine allows them to use the caster's resources such as the bonus action.

**Comment by Rumsarr** [comment]
my though on that was give the artificer a spell that 'loads' the cannon, and the cannon can only fire if it has that buff. Is it a work around? Yes. Can it be done? No idea.

**Comment by Rumsarr** [comment]
But yes, later is good.

**Comment by Pacted** [comment]
As long as the cannon spawns loaded, that wouldn't be a problem and would in my opinion make more sense than spawning an empty cannon

**Comment by Rumsarr** [comment]
that would fix the potential problem

**Comment by Kidel** [comment]
found a trick to make it follow you (made as a raven, polymrphed as a turret) and even gave it the fly spell for now. We'll playtest it. 

At the moment it's learned by BattleSmith at level 3, needs to be moved to Artillerist

**Comment by Kidel** [comment]
is anybody working on the Tiny Cannon?

**Comment by Kidel** [comment]
made the tiny cannon.

**Comment by Rumsarr** [comment]
Something to talk about after the first release is to think about maybe adding more abilities to the cannon at later levels. depending on how balance goes of course.
