### ISSUE TITLE
Implement Arcane Firearm

### ISSUE THREAD

**Issue by Pacted** [Kidel/BG3_Artificer#33]
similar to Pact Weapon, gives 1 extra d8 damage to spells passive

**Comment by Rumsarr** [comment]
How would that translate to multiple shot spells?  Magic missile, scorching ray, eldritch blast can all target multiple targets individually.

**Comment by AnxietyTheOrk** [comment]
> How would that translate to multiple shot spells?  Magic missile, scorching ray, eldritch blast can all target multiple targets individually. 

Not sure yet. Last I checked, there wasn't a clear ruling on that, even Jeremy Crawford's tweet from years ago had confusion in the comments.

**Comment by Rumsarr** [comment]
On deeper reflection I think it will be ok.  The artillerist class is suppose to be a 'blaster' type class.  They are also a 1/2 caster with very few spell slots. The class, by level 12, will only have 3 third level and 2 second levell spell slots.  I think that is where the balance is.

**Comment by Kidel** [comment]
it applies on "spell cast". I'd add a single d8 to multihit spells. As a master I'd also feel that having a 5th level passive roll 10d8 with max level magic missile is stupid.

**Comment by Rumsarr** [comment]
at max level (12) artificers max spell slot is 3rd level.

**Comment by Rumsarr** [comment]
and only 3 slots at that.

**Comment by Kidel** [comment]
5 darts doing 5d4 + 5d8 with no attack roll or save with a 3rd level spell slot is stupid.

**Comment by Rumsarr** [comment]
Powerful for sure. but its also as hard as the artificer can hit at max level.   Compared to the other classes?   the monk doing 9 attacks per turn?  is it really that much more powerful?

**Comment by Kidel** [comment]
also you can easily get 5th level in artificer, then do 7 more level with wizard and use 4th level slots and get all the wizard's modifiers + 6d4 + 6d8 +6 of damage on an impossible to avoid spell.

Again, description says "per cast" and the spell is cast only once. At least in BG3 scripts that's clear. 

It would also be complicated to do apply it per hit

**Comment by Kidel** [comment]
Artificer has plenty of ways to do crazy damage. Not necessarily with spells. It's not a Sorcerer.

**Comment by Rumsarr** [comment]
Just pointing things out is all I'm doing.  If need be we can change it later.  Maybe make it a later lvl skill i donno.

**Comment by Rumsarr** [comment]
or stage it.   1d4 to start then 1d8 at later levels.

**Comment by Kidel** [comment]
I'm not changing stuff unless there is real benefit to it.
Having to overcomplicate the implementation and then having to scale it down just to fit a rule that doesn't exist is not something I'm willing to waste time over.
