### ISSUE TITLE
Implement Spell/cantrip progression for Armorsmith up to level 12

### ISSUE THREAD

**Issue by Kidel** [Kidel/BG3_Artificer#4]
use comments or placeholder skills for missing ones

**Comment by kreios86** [comment]
Ill grab this one.

**Comment by kreios86** [comment]
Pushed the skeletons. Need to fully implement the container for Armor Model.

**Comment by Kidel** [comment]
@kreios86 armor model? Didn't we say it was a buff on existing armor?
