### ISSUE TITLE
Embellish Progression

### ISSUE THREAD

**Issue by Kidel** [Kidel/BG3_Artificer#42]
Find a way to add titles and descriptions to progression sections

**Comment by Rumsarr** [comment]
I'm honestly not a coder but if someone needs descriptions of gear or abilities I'm more than willing to help out.

**Comment by Kidel** [comment]
this issue is more like "how do we link those descriptions to progression steps"

**Comment by Kidel** [comment]
![Image](https://github.com/Kidel/BG3_Artificer/assets/3390842/894bca72-b59a-4514-a704-df97859d8ae4)
