### ISSUE TITLE
Right Tool for the Job Issues

### ISSUE THREAD

**Issue by chriseggroll** [Kidel/BG3_Artificer#77]
Right Tool for the Job  lets you pick from shovel, trap disarm kit and thieves' tools but none of these seem to work right now - no item in inventory, nothing on the ground and the class action doesn't go on cooldown.

**Comment by Kidel** [comment]
works on my version of the mod, 1.6.1. I can't reproduce this :(

**Comment by Kidel** [comment]
Video proof: https://imgur.com/6Okvlui

**Comment by chriseggroll** [comment]
Found the problem, seems to be a conflict with Cleric Subclasses mod.  Both use improvedUI Assets so it must be one of those files.  It's a pretty minor feature so I'll just ignore it, everything else seems to work fine and I'm playing Shadowheart as Twilight 🤷

**Comment by Kidel** [comment]
Seems that the Cleric mod was updated to rely on ImprovedUI Assets too, so it shouldn't give you issues if you get the updated version.

**Comment by chriseggroll** [comment]
I'm using the latest version, still doesn't work.  I've tried changing the order by no difference except removing cleric subclasses completely.

**Comment by Kidel** [comment]
are you using the correct modfixer and removed the old ones? Have you removed the mod that blocks the warning message? Have you updated to the latest improcedUI?

**Comment by chriseggroll** [comment]
looks like you figured it out, thank you.
