### ISSUE TITLE
Make Armorsmith Gauntlets actual gauntlets to be equipped as main hannd and offhand

### ISSUE THREAD

**Issue by Kidel** [Kidel/BG3_Artificer#79]
We should have the gauntlets as equippable items in main hand and offhand so that you can use infusions on them and they work with other feats.

We then have to make them a requirement for armorer's skill (they give a buff that's added as requirement for the attack abilities) and disappear on respec similarily to pact weapons.

**Comment by RezzMage** [comment]
If you get this to work, can you do the same with the lightning launchers? The way they are now, they don't work with the Sharpshooter feat (and I assume Sneak Attack, but I haven't tested that yet).

**Comment by Kidel** [comment]
done in 1.10
