### ISSUE TITLE
Artificer enthusiast wanting to help

### ISSUE THREAD

**Issue by Rumsarr** [Kidel/BG3_Artificer#8]
I signed up got Github to also try to help.  I do have no knowledge about coding but I'm a DnD GM that homebrews a lot.  I might have some insight on replacement mechanics, substitute spells/systems and I got plenty of time for testing if you all will have me.

**Comment by Kidel** [comment]
welcome aboard, contact any of us on discord to get added to the group chat.

**Comment by DrBoskonovitch** [comment]
Is the group chat in the official Larian channel?

**Comment by Kidel** [comment]
we don't have permissions to do it. While we started from that server, our group chat is a normal private group chat on discord.

**Comment by Rumsarr** [comment]
Ok how do i get to this chat room?
Rumsar is my name on discord

**Comment by Kidel** [comment]
sent you a friend request
