### ISSUE TITLE
Make a copy of Ketheric's dog with altered textures and size to be used as second Steel Defender

### ISSUE THREAD

**Issue by Kidel** [Kidel/BG3_Artificer#80]
Title says it all

**Comment by Kidel** [comment]
this is not possible until we get tools to extract virtual textures

**Comment by anticode-403** [comment]
I can extract the virtual textures. What is the ID for the dog?

**Comment by Kidel** [comment]
it's among our root templates

**Comment by Kidel** [comment]
@anticode-403 did you find it?

**Comment by Kidel** [comment]
Artificer\Public\Artificer\RootTemplates\777a1689-9707-4358-bc2b-075e8520cef8.lsx

**Comment by anticode-403** [comment]
Sorry, wasn't able to look for a few days. That was a bit of a rabbit hole but I found the Visual Texture file names
DOG_SkeletalHound_Head: 58ad318cb8f2d20fb3b7078b756b5ee4
DOG_SkeletalHound_Body: 56b93558007cbc2c8065f86e79b236ab
DOG_SkeletalHound_Legs: 04cc33ea0c7d61d10fa7c4110b32a253
DOG_SkeletalHound_Metal: 9bdeeda058755114215ec27e53d025c1

If you give me a few extra days, I could probably kitbash together a purely metal version of the model.

**Comment by anticode-403** [comment]
If you want the textures more directly, I can send them to you but doing it over GitHub is probably not the best method.

**Comment by Kidel** [comment]
@anticode-403 it would be great if you could make a PR with the textures converted to DDS and the lsx files to make the model use them instead of the virtual ones

**Comment by Kidel** [comment]
We are attempting to use the Shadow Mastiff. Closing this one
