### ISSUE TITLE
Artillerist's Eldritch Cannon Flamethrower requires Concentration

### ISSUE THREAD

**Issue by Pherrell** [Kidel/BG3_Artificer#82]
The Artillerist's Eldritch Cannon Flamethrower requires Concentration. It doesn't matter as much on the small version as it doesn't have anything to concentrate on. But for the tiny one, it means you can't use that ability without dropping a spell you're concentrating on.

**Comment by Kidel** [comment]
yep an extra flag was requiring concentration. Will be fixed in 1.10.2
