### ISSUE TITLE
Magic Item Savant

### ISSUE THREAD

**Issue by Kidel** [Kidel/BG3_Artificer#84]
```
Magic Item Savant

At 14th level, your skill with magic items deepens more:

    You can attune to up to five magic items at once.

    You ignore all class, race, spell and level requirements on attuning to or using a magic item.
```

Useless in BG3.
Thinking about the impact many attuned items might have in a campaign I'd say +1 AC if you got a magic armor and +1 attack roll and damage rolls (as well as spell damage rolls) if you're wielding a magic weapon.

**Comment by Kidel** [comment]
uhm nope, seems no armor in the game got the magical property

**Comment by edoipi** [comment]
It could give special effects when using magical items that are race restricted. There are plenty of items that has extra effects when used by Githyanki and at least one gloves that work only on Dwarves, Halflings and Goneomes.

**Comment by Kidel** [comment]
I think that would require redefining those magical items or adding race tags to artificer, which would cause trouble indialogues.

**Comment by edoipi** [comment]
Might be more effort than worth it.

**Comment by Kidel** [comment]
Only thing I can think of is to give a +1 to spell damage and a +1 to weapon attack if you have a magic weapon equipped.

To appeal to both playstyles.

**Comment by Kidel** [comment]
we could add an optional file for the  "You ignore all class, race, spell and level requirements on attuning to or using a magic item" effect where we override original game items/boosts

**Comment by Kidel** [comment]
this one only misses the optional addon that overwrites race specific items. Will be done at the very end.

**Comment by Kidel** [comment]
I also just had a flash of genius of a way to implement magic item savant without replacing all items with racial features
we could probably just add a passive that checks if the item X is equipped and just gives a copy of the effect if the tag is missing from the character, like "has gith sword equipped and not tagged gith -> give the same effect the item would have given"
